name: .NET

on:
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: List directory contents
      run: ls -R
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies 
      run: dotnet restore QuadraticEquationSolver/QuadraticEquationSolver.sln
    - name: Build 
      run: dotnet build --no-restore QuadraticEquationSolver/QuadraticEquationSolver.sln
    - name: Test 
      run: dotnet test --no-restore --verbosity normal QuadraticEquationSolver/QuadraticEquationSolver.sln
